package gui;

import domain.Cancion;
import domain.Message;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Angel Marin
 */
public class GUIMensajes extends javax.swing.JFrame {

    DefaultListModel<String> onlineUsers;
    DefaultComboBoxModel usersToSend;
    IChat chat;
    String userOnline;
    
    /**
     * Crea la GUI de mensajes
     */
    public GUIMensajes(IChat chat) {
        initComponents();
        onlineUsers = new DefaultListModel();
        usersToSend = new DefaultComboBoxModel();
        liOnlineUsers.setModel(onlineUsers);
        cbSendTo.setModel(usersToSend);
        addUserToSend("TODOS");
        this.setVisible(true);
        
        this.chat = chat;
    }
    
    public void setOnlineUserID(String userId){
        this.lblUserId.setText(userId);
        userOnline = userId;
    }
    
    public void addOnlineUser(String user){
        onlineUsers.addElement(user);
    }
    
    public void removeOnlineUser(String user){
        int userPosition = onlineUsers.indexOf(user);
        onlineUsers.remove(userPosition);
    }
    
    public void addUserToSend(String user){
        usersToSend.addElement(user);
    }
    
    public void removeUserToSend(String user){
        int userPosition = usersToSend.getIndexOf(user);
        usersToSend.removeElement(user);
        
    }
    
    public void addMessage(String message){
        tareaMessages.append(message +  "\n");
    }
    
    public void constructMessage(){
        
        String from = userOnline;
        String to = getTargetUser();
        String command = "add:msg";
        String message = tareaMessage.getText();
        
        Message messageToSend = new Message(from, to, command, message);
        
        chat.sendMessageAll(messageToSend);
    }
    
    private String getTargetUser(){
        
        String target = (String) cbSendTo.getSelectedItem();
        
        if(target.equalsIgnoreCase("TODOS")){
            target = "All";
        }
        
        return target;
    }
    
    public void addCancion(Cancion cancion){
        DefaultTableModel model = (DefaultTableModel) tblSongs.getModel();
        model.addRow(new Object[]{cancion.getNombre() , cancion.getAutor()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlMain = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        userChat = new javax.swing.JPanel();
        lblLoggedAs = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        spMessage = new javax.swing.JScrollPane();
        tareaMessage = new javax.swing.JTextArea();
        lblMessage = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        cbSendTo = new javax.swing.JComboBox<>();
        lblSendTo = new javax.swing.JLabel();
        pnlOnlineUsers = new javax.swing.JPanel();
        lblOnlineUsers = new javax.swing.JLabel();
        spOnlineUsers = new javax.swing.JScrollPane();
        liOnlineUsers = new javax.swing.JList<>();
        pnlSongsTable = new javax.swing.JPanel();
        spSongsTable = new javax.swing.JScrollPane();
        tblSongs = new javax.swing.JTable();
        lblSongReceived = new javax.swing.JLabel();
        pnlMessages = new javax.swing.JPanel();
        spMessages = new javax.swing.JScrollPane();
        tareaMessages = new javax.swing.JTextArea();
        lblMessages = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chat");
        lblTitle.setFocusable(false);
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(239, 239, 239))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLoggedAs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoggedAs.setText("Conectado Como:");

        lblUserId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserId.setText("#USERID#");

        tareaMessage.setColumns(20);
        tareaMessage.setRows(5);
        spMessage.setViewportView(tareaMessage);

        lblMessage.setText("Mensaje:");

        btnSend.setText("Enviar");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendClicked(evt);
            }
        });

        cbSendTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSendTo.setText("Enviar a:");

        javax.swing.GroupLayout userChatLayout = new javax.swing.GroupLayout(userChat);
        userChat.setLayout(userChatLayout);
        userChatLayout.setHorizontalGroup(
            userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMessage)
                    .addGroup(userChatLayout.createSequentialGroup()
                        .addGroup(userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userChatLayout.createSequentialGroup()
                                .addComponent(lblLoggedAs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserId))
                            .addComponent(lblMessage))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(userChatLayout.createSequentialGroup()
                        .addComponent(lblSendTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSendTo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        userChatLayout.setVerticalGroup(
            userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userChatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedAs)
                    .addComponent(lblUserId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSendTo)
                    .addComponent(cbSendTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addGap(12, 12, 12))
        );

        pnlOnlineUsers.setMaximumSize(new java.awt.Dimension(200, 32767));

        lblOnlineUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOnlineUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOnlineUsers.setText("Usuarios Online");

        liOnlineUsers.setMaximumSize(new java.awt.Dimension(200, 0));
        spOnlineUsers.setViewportView(liOnlineUsers);

        javax.swing.GroupLayout pnlOnlineUsersLayout = new javax.swing.GroupLayout(pnlOnlineUsers);
        pnlOnlineUsers.setLayout(pnlOnlineUsersLayout);
        pnlOnlineUsersLayout.setHorizontalGroup(
            pnlOnlineUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOnlineUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOnlineUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spOnlineUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblOnlineUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOnlineUsersLayout.setVerticalGroup(
            pnlOnlineUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOnlineUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOnlineUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spOnlineUsers)
                .addContainerGap())
        );

        tblSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spSongsTable.setViewportView(tblSongs);

        lblSongReceived.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSongReceived.setText("Canciones Recibidas:");

        javax.swing.GroupLayout pnlSongsTableLayout = new javax.swing.GroupLayout(pnlSongsTable);
        pnlSongsTable.setLayout(pnlSongsTableLayout);
        pnlSongsTableLayout.setHorizontalGroup(
            pnlSongsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongsTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSongsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSongsTableLayout.createSequentialGroup()
                        .addComponent(lblSongReceived)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spSongsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSongsTableLayout.setVerticalGroup(
            pnlSongsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSongsTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSongReceived)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSongsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        spMessages.setFocusable(false);

        tareaMessages.setColumns(20);
        tareaMessages.setRows(5);
        spMessages.setViewportView(tareaMessages);

        lblMessages.setText("Mensajes:");

        javax.swing.GroupLayout pnlMessagesLayout = new javax.swing.GroupLayout(pnlMessages);
        pnlMessages.setLayout(pnlMessagesLayout);
        pnlMessagesLayout.setHorizontalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMessagesLayout.createSequentialGroup()
                        .addComponent(lblMessages)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spMessages))
                .addContainerGap())
        );
        pnlMessagesLayout.setVerticalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSongsTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMessages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOnlineUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOnlineUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(userChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSongsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendClicked
        constructMessage();
    }//GEN-LAST:event_btnSendClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cbSendTo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLoggedAs;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessages;
    private javax.swing.JLabel lblOnlineUsers;
    private javax.swing.JLabel lblSendTo;
    private javax.swing.JLabel lblSongReceived;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JList<String> liOnlineUsers;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMessages;
    private javax.swing.JPanel pnlOnlineUsers;
    private javax.swing.JPanel pnlSongsTable;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane spMessage;
    private javax.swing.JScrollPane spMessages;
    private javax.swing.JScrollPane spOnlineUsers;
    private javax.swing.JScrollPane spSongsTable;
    private javax.swing.JTextArea tareaMessage;
    private javax.swing.JTextArea tareaMessages;
    private javax.swing.JTable tblSongs;
    private javax.swing.JPanel userChat;
    // End of variables declaration//GEN-END:variables
}
